apiVersion: apps/v1
kind: Deployment
metadata:
  name: queueflow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queueflow-api
  template:
    metadata:
      labels:
        app: queueflow-api
    spec:
      containers:
        - name: api
          image: queueflow-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis
---
apiVersion: v1
kind: Service
metadata:
  name: queueflow-api
spec:
  selector:
    app: queueflow-api
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
