apiVersion: apps/v1
kind: Deployment
metadata:
  name: queueflow-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queueflow-worker
  template:
    metadata:
      labels:
        app: queueflow-worker
    spec:
      containers:
        - name: worker
          image: queueflow-worker:latest
          imagePullPolicy: Never
          env:
            - name: REDIS_HOST
              value: redis
